In [1]:
import pandas as pd
df = pd.read_excel("/content/Project SQL.xlsx")

1.**Country code extracted from order id column**

In [2]:
df["Order ID"]

0       CA-2017-167976
1       CA-2017-165099
2       US-2015-147662
3       CA-2017-109757
4       CA-2014-111360
             ...
9689    CA-2015-112014
9690    CA-2016-106621
9691    CA-2016-134222
9692    CA-2016-108224
9693    CA-2017-159282
Name: Order ID, Length: 9694, dtype: object

**2.Get the top 5 profit from sales for each city wise**

In [13]:
df.loc[df.City=="Akron"][df.Profit==df.Profit.max()]

<ipython-input-13-056640a0c11a>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df.loc[df.City=="Akron"][df.Profit==df.Profit.max()]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, rk, Sales Category]
Index: []

[0 rows x 23 columns]

In [ ]:
print(df[['City','Sales','Profit']][df.City=="Aberdeen"][df.Profit== df.Profit.max()].head(5))

Empty DataFrame
Columns: [City, Sales, Profit]
Index: []

<ipython-input-11-839b116aca4b>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(df[['City','Sales','Profit']][df.City=="Aberdeen"][df.Profit== df.Profit.max()].head(5))

3.**Extract the maximum values using row number function**

In [14]:
print(df['Row ID'].nlargest())

9594    9994
1587    9993
1596    9992
1590    9991
4871    9990
Name: Row ID, dtype: int64

In [ ]:
print(df['Row ID'].max())

9994

In [4]:
df[['City','State']]

          City         State
0     Aberdeen  South Dakota
1      Abilene         Texas
2        Akron          Ohio
3        Akron          Ohio
4        Akron          Ohio
...        ...           ...
9689   Yucaipa    California
9690      Yuma       Arizona
9691      Yuma       Arizona
9692      Yuma       Arizona
9693      Yuma       Arizona

[9694 rows x 2 columns]

**4.Remove duplicates from city , state**

In [5]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9689    False
9690    False
9691    False
9692    False
9693    False
Length: 9694, dtype: bool

**5.Segment wise sales which is greater than 500**

In [6]:
df[['Row ID','Sales']][df.Sales > 500]

      Row ID     Sales
22       455   665.408
36      2417   595.000
50      3281  4164.050
61      9190   663.072
72      1439  2453.430
...      ...       ...
9664    2845   845.488
9681    5298   543.920
9682    1083   836.592
9683    1086  4899.930
9693    7282   599.985

[1151 rows x 2 columns]

**6.Category Sales 0 - 100 as low , 101 - 500 medium , 500 - 2000 as high , > 2000  as best**

In [7]:
import numpy as np
df.loc[(df.Sales >=0) & (df.Sales <100),'Sales Category']="LOW"
df.loc[(df.Sales >100) & (df.Sales <= 500),'Sales Category']="MEDIUM"
df.loc[(df.Sales >500) & (df.Sales <= 2000),'Sales Category']="HIGH"
df.loc[(df.Sales >2000) ,'Sales Category']="BEST"
df[['Sales','Sales Category']]

        Sales Sales Category
0      25.500            LOW
1       1.392            LOW
2       2.286            LOW
3       4.368            LOW
4       5.742            LOW
...       ...            ...
9689   50.800            LOW
9690   10.496            LOW
9691   44.856            LOW
9692  185.528         MEDIUM
9693  599.985           HIGH

[9694 rows x 2 columns]

7**.city , region wise sum of sales , profits , count of sales & profits**

In [ ]:
Region_list=df.groupby('Region').groups.keys()
print(len(Region_list))
print( df.groupby('Region').get_group('Central'))

4
      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0       9261  CA-2017-167976 2017-11-11      43053    Second Class
1       6990  CA-2017-165099 2017-12-11      43082     First Class
51      1568  CA-2015-129112 2015-11-29      42338     First Class
52      2976  CA-2015-137512 2015-05-07      42136  Standard Class
53      1567  CA-2015-129112 2015-11-29      42338     First Class
...      ...             ...        ...        ...             ...
9655    5350  CA-2015-149811 2015-01-04      42014  Standard Class
9656    8737  CA-2016-168774 2016-09-04      42622  Standard Class
9660    2572  CA-2017-109778 2017-07-16      42937  Standard Class
9661    2883  CA-2014-165540 2014-02-21      41695  Standard Class
9664    2845  US-2016-162852 2016-12-27      42735  Standard Class

     Customer ID      Customer Name      Segment        Country       City  \
0       JL-15505    Jeremy Lonsdale     Consumer  United States   Aberdeen
1       DK-13375        Dennis Kane     Consumer  United States    Abilene
51      AW-10840       Anthony Witt     Consumer  United States      Allen
52      AG-10675        Anna Gayman     Consumer  United States      Allen
53      AW-10840       Anthony Witt     Consumer  United States      Allen
...          ...                ...          ...            ...        ...
9655    CS-12250    Chris Selesnick    Corporate  United States   Woodbury
9656    RP-19855           Roy Phan    Corporate  United States   Woodbury
9660    VM-21685    Valerie Mitchum  Home Office  United States  Woodstock
9661    TM-21010     Tamara Manning     Consumer  United States  Woodstock
9664    BG-11695  Brooke Gillingham    Corporate  United States  Woodstock

      ...       Product ID         Category Sub-Category  \
0     ...  OFF-SU-10004661  Office Supplies     Supplies
1     ...  OFF-AP-10001634  Office Supplies   Appliances
51    ...  OFF-BI-10000088  Office Supplies      Binders
52    ...  OFF-PA-10000213  Office Supplies        Paper
53    ...  TEC-AC-10003038       Technology  Accessories
...   ...              ...              ...          ...
9655  ...  OFF-PA-10004082  Office Supplies        Paper
9656  ...  OFF-ST-10001490  Office Supplies      Storage
9660  ...  OFF-AR-10003759  Office Supplies          Art
9661  ...  OFF-BI-10004094  Office Supplies      Binders
9664  ...  FUR-CH-10004853        Furniture       Chairs

                                           Product Name    Sales Quantity  \
0                         Acme Titanium Bonded Scissors   25.500        3
1          Hoover Commercial Lightweight Upright Vacuum    1.392        2
51                               GBC Imprintable Covers    8.784        4
52                                            Xerox 198   15.936        4
53           Kingston Digital DataTraveler 16GB USB 2.0   21.480        3
...                                                 ...      ...      ...
9655  Adams Telephone Message Book w/Frequently-Call...   39.900        5
9656                     Hot File 7-Pocket, Floor Stand  535.410        3
9660                   Crayola Anti Dust Chalk, 12/Pack    2.912        2
9661         GBC Standard Plastic Binding Systems Combs    8.850        5
9664      Global Manager's Adjustable Task Chair, Storm  845.488        8

     Discount    Profit  rk  Sales Category
0         0.0    6.6300   1             LOW
1         0.8   -3.7584   1             LOW
51        0.8  -13.6152   1             LOW
52        0.2    5.3784   2             LOW
53        0.2   -0.2685   3             LOW
...       ...       ...  ..             ...
9655      0.0   19.9500   2             LOW
9656      0.0  160.6230   3            HIGH
9660      0.2    0.9100   1             LOW
9661      0.8  -13.7175   2             LOW
9664      0.3  -12.0784   5            HIGH

[2260 rows x 23 columns]

In [ ]:
print(df.groupby('City').ngroups)

529

In [ ]:
df['Sales']

0        25.500
1         1.392
2         2.286
3         4.368
4         5.742
         ...
9689     50.800
9690     10.496
9691     44.856
9692    185.528
9693    599.985
Name: Sales, Length: 9694, dtype: float64

In [ ]:
sum_sales={}
for Region in df['Region'].unique():
  tempdf = df[df['Region']==Region]
  sum_sale= tempdf['Sales'].sum()
  sum_sales['Region_list']=sum_sale
  aggregate_df=pd.DataFrame.from_dict(sum_sales,orient='index',columns=['Sales for Region'])
  print(aggregate_df)

             Sales for Region
Region_list       497800.8728
             Sales for Region
Region_list        672194.054
             Sales for Region
Region_list       713471.3445
             Sales for Region
Region_list        388983.585

In [ ]:
sum_tot=df.groupby('Region')['Sales'].sum()
print(sum_tot)

Region
Central    497800.8728
East       672194.0540
South      388983.5850
West       713471.3445
Name: Sales, dtype: float64

In [ ]:
profit_tot=df.groupby('Region')['Profit'].sum()
print(profit_tot)

Region
Central     40128.9030
East        90672.0127
South       46035.6890
West       106021.1495
Name: Profit, dtype: float64

In [ ]:
print(df.groupby('Sales').ngroups)

5696

In [ ]:
print(df.groupby('Profit').ngroups)

7076

**8.Select all the records belongs to region east & west with sales > 500**

In [ ]:
 df[(df['Region']=='East') & (df['Sales']> 500)] ,df[['Region','Sales']]

(      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
 22       455  CA-2017-147277 2017-10-20      43032  Standard Class
 61      9190  US-2015-130512 2015-08-21      42241  Standard Class
 267      989  CA-2017-167899 2017-05-21      42881  Standard Class
 435     5695  US-2015-138093 2015-12-10      42354  Standard Class
 436     7184  CA-2017-128853 2017-04-21      42848     First Class
 ...      ...             ...        ...        ...             ...
 9647    5395  US-2014-123183 2014-11-19      41968  Standard Class
 9648    4941  CA-2015-156482 2015-02-06      42048  Standard Class
 9681    5298  CA-2017-108791 2017-07-27      42947  Standard Class
 9682    1083  US-2016-143819 2016-03-01      42434  Standard Class
 9683    1086  US-2016-143819 2016-03-01      42434  Standard Class

      Customer ID      Customer Name      Segment        Country        City  \
 22      EB-13705         Ed Braxton    Corporate  United States       Akron
 61      SM-20320        Sean Miller  Home Office  United States   Allentown
 267     JG-15805         John Grady    Corporate  United States      Auburn
 435     KM-16225       Kalyca Meade    Corporate  United States   Baltimore
 436     JM-15250       Janet Martin     Consumer  United States   Baltimore
 ...          ...                ...          ...            ...         ...
 9647    GR-14560  Georgia Rosenberg    Corporate  United States  Wilmington
 9648    IL-15100        Ivan Liston     Consumer  United States  Wilmington
 9681    TM-21490      Tony Molinari     Consumer  United States     Yonkers
 9682    KD-16270      Karen Daniels     Consumer  United States     Yonkers
 9683    KD-16270      Karen Daniels     Consumer  United States     Yonkers

       ...       Product ID         Category Sub-Category  \
 22    ...  OFF-ST-10000142  Office Supplies      Storage
 61    ...  OFF-ST-10002574  Office Supplies      Storage
 267   ...  FUR-FU-10004071        Furniture  Furnishings
 435   ...  FUR-CH-10000785        Furniture       Chairs
 436   ...  FUR-CH-10004218        Furniture       Chairs
 ...   ...              ...              ...          ...
 9647  ...  FUR-BO-10000362        Furniture    Bookcases
 9648  ...  FUR-CH-10001708        Furniture       Chairs
 9681  ...  TEC-PH-10002660       Technology       Phones
 9682  ...  FUR-TA-10001095        Furniture       Tables
 9683  ...  TEC-MA-10003979       Technology     Machines

                                            Product Name     Sales Quantity  \
 22             Deluxe Rollaway Locking File with Drawer   665.408        2
 61                SAFCO Commercial Wire Shelving, Black   663.072        6
 267   Luxo Professional Magnifying Clamp-On Fluoresc...   520.050        5
 435                     Global Ergonomic Managers Chair   542.940        3
 436            Global Fabric Manager's Chair, Dark Gray   908.820        9
 ...                                                 ...       ...      ...
 9647                 Sauder Inglewood Library Bookcases  1025.880        6
 9648  Office Star - Contemporary Swivel Chair with P...  1268.820        9
 9681                    Nortel Networks T7316 E Nt8 B27   543.920        8
 9682                 Chromcraft Round Conference Tables   836.592        8
 9683                  Ativa V4110MDD Micro-Cut Shredder  4899.930        7

      Discount     Profit  rk  Sales Category
 22        0.2    66.5408  21            HIGH
 61        0.2  -165.7680   7            HIGH
 267       0.0    72.8070  22            HIGH
 435       0.0   141.1644  40            HIGH
 436       0.0   227.2050  41            HIGH
 ...       ...        ...  ..             ...
 9647      0.0   235.9524  34            HIGH
 9648      0.0   266.4522  35            HIGH
 9681      0.0   135.9800  13            HIGH
 9682      0.4  -264.9208  14            HIGH
 9683      0.0  2400.9657  15            BEST

 [331 rows x 23 columns],
        Region    Sales
 0     Central   25.500
 1     Central    1.392
 2        East    2.286
 3        East    4.368
 4        East    5.742
 ...       ...      ...
 9689     West   50.800
 9690     West   10.496
 9691     West   44.856
 9692     West  185.528
 9693     West  599.985

 [9694 rows x 2 columns])

In [8]:
df[(df['Region']=='West') & (df['Sales']> 500)] ,df[['Region','Sales']]

(      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
 36      2417  CA-2017-168655 2017-10-12      43026  Standard Class
 94      9908  US-2015-129007 2015-09-13      42262     First Class
 95      7058  CA-2016-165330 2016-12-11      42715        Same Day
 96      9943  CA-2014-143371 2014-12-28      42007  Standard Class
 97      5871  CA-2016-128223 2016-06-14      42535        Same Day
 ...      ...             ...        ...        ...             ...
 9440    8784  CA-2016-116911 2016-09-15      42633  Standard Class
 9463     639  CA-2016-115917 2016-05-20      42515  Standard Class
 9597    9180  CA-2017-156776 2017-08-07      42958  Standard Class
 9598    9187  CA-2017-156776 2017-08-07      42958  Standard Class
 9693    7282  CA-2017-159282 2017-10-16      43029  Standard Class

      Customer ID      Customer Name      Segment        Country         City  \
 36      ML-18040  Michelle Lonsdale    Corporate  United States  Albuquerque
 94      KD-16615           Ken Dana    Corporate  United States      Anaheim
 95      WB-21850      William Brown     Consumer  United States      Anaheim
 96      MD-17350      Maribeth Dona     Consumer  United States      Anaheim
 97      EB-13705         Ed Braxton    Corporate  United States      Anaheim
 ...          ...                ...          ...            ...          ...
 9440    JD-16150   Justin Deggeller    Corporate  United States   Twin Falls
 9463    RB-19465       Rick Bensley  Home Office  United States      Vallejo
 9597    JL-15505    Jeremy Lonsdale     Consumer  United States  Westminster
 9598    JL-15505    Jeremy Lonsdale     Consumer  United States  Westminster
 9693    GH-14410        Gary Hansen  Home Office  United States         Yuma

       ...       Product ID         Category Sub-Category  \
 36    ...  TEC-AC-10002842       Technology  Accessories
 94    ...  FUR-CH-10000155        Furniture       Chairs
 95    ...  FUR-TA-10004619        Furniture       Tables
 96    ...  OFF-ST-10001128  Office Supplies      Storage
 97    ...  FUR-TA-10001771        Furniture       Tables
 ...   ...              ...              ...          ...
 9440  ...  FUR-TA-10003473        Furniture       Tables
 9463  ...  FUR-FU-10000576        Furniture  Furnishings
 9597  ...  TEC-PH-10002415       Technology       Phones
 9598  ...  OFF-AP-10002534  Office Supplies   Appliances
 9693  ...  TEC-MA-10001148       Technology     Machines

                                            Product Name     Sales Quantity  \
 36    WD My Passport Ultra 2TB Portable External Har...   595.000        5
 94                  Global Comet Stacking Armless Chair   717.720        3
 95                       Hon Non-Folding Utility Tables   892.136        7
 96          Carina Mini System Audio Rack, Model AR050B   998.820        9
 97        Bush Cubix Conference Tables, Fully Assembled  1293.488        7
 ...                                                 ...       ...      ...
 9440         Bretford Rectangular Conference Table Tops  1128.390        3
 9463  Luxo Professional Fluorescent Magnifier Lamp w...  1049.200        5
 9597          Polycom VoiceStation 500 ConferenceÂ phone   707.880        3
 9598  3.6 Cubic Foot Counter Height Office Refrigerator  1473.100        5
 9693       Swingline SM12-08 MicroCut Jam Free Shredder   599.985        5

      Discount    Profit  rk  Sales Category
 36        0.0   95.2000  14            HIGH
 94        0.2   71.7720  22            HIGH
 95        0.2  111.5170  23            HIGH
 96        0.0   29.9646  24            HIGH
 97        0.2   80.8430  25            HIGH
 ...       ...       ...  ..             ...
 9440      0.0  259.5297   2            HIGH
 9463      0.0  272.7920   6            HIGH
 9597      0.2   44.2425  14            HIGH
 9598      0.0  412.4680  15            HIGH
 9693      0.7 -479.9880   4            HIGH

 [367 rows x 23 columns],
        Region    Sales
 0     Central   25.500
 1     Central    1.392
 2        East    2.286
 3        East    4.368
 4        East    5.742
 ...       ...      ...
 9689     West   50.800
 9690     West   10.496
 9691     West   44.856
 9692     West  185.528
 9693     West  599.985

 [9694 rows x 2 columns])

**9.create 'Rank' by city**

In [ ]:
df["Rank"] = df['City'].rank()
df.sort_values('City',inplace=True)
df[['City','Rank']]

          City    Rank
0     Aberdeen     1.0
1      Abilene     2.0
2        Akron    13.0
3        Akron    13.0
4        Akron    13.0
...        ...     ...
9689   Yucaipa  9690.0
9692      Yuma  9692.5
9690      Yuma  9692.5
9691      Yuma  9692.5
9693      Yuma  9692.5

[9694 rows x 2 columns]

**Dense Rank by Sales**

In [ ]:
df["Dense Rank"] = df['Sales'].rank(method = 'dense').astype(int)
df[['Dense Rank','Sales']]

      Dense Rank    Sales
0           1444   25.500
1             21    1.392
22          5013  665.408
20          4182  284.364
19          4168  279.960
...          ...      ...
9689        2227   50.800
9690         670   10.496
9691        2081   44.856
9692        3699  185.528
9693        4924  599.985

[9694 rows x 2 columns]

 ***LEFT OUTER JOIN:***

 In left outer join of 2 data frames,the first (left) data frame will print as it is.
 And the second data frame the values which is common in first data frame only printed.

# **We use MERGE method and how ='left'**

 ***RIGHT OUTER JOIN:***


 In Right outer join of 2 data frames,the Second (right) data frame will print as it is.
 And the first data frame the values which is common in second data frame only printed.

# **We use MERGE method and how ='right'**

**INNER JOIN:**

In inner join function, with the 2 data frames the common values in both data frames only printed

# **We use MERGE method and how ='inner'**


**OUTER JOIN:**

In 2 data frames , the outer join print all the values in both data frames and fill NAN values in which there is no common values.

# **We use MERGE method and how ='outer'**